apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-service
  namespace: onlineboutique
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog-service
  template:
    metadata:
      labels:
        app: product-catalog-service
    spec:
      containers:
      - name: product-catalog-service
        image: onlineboutique/product-catalog-service:latest
        ports:
        - containerPort: 3550
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DATABASE_URL
          value: "jdbc:postgresql://postgres:5432/onlineboutique"
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 3550
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 3550
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  namespace: onlineboutique
spec:
  selector:
    app: product-catalog-service
  ports:
  - port: 3550
    targetPort: 3550
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-service
  namespace: onlineboutique
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-service
  template:
    metadata:
      labels:
        app: currency-service
    spec:
      containers:
      - name: currency-service
        image: onlineboutique/currency-service:latest
        ports:
        - containerPort: 3551
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DATABASE_URL
          value: "jdbc:postgresql://postgres:5432/onlineboutique"
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 3551
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 3551
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: currency-service
  namespace: onlineboutique
spec:
  selector:
    app: currency-service
  ports:
  - port: 3551
    targetPort: 3551
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: onlineboutique
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: onlineboutique/cart-service:latest
        ports:
        - containerPort: 3552
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DATABASE_URL
          value: "jdbc:postgresql://postgres:5432/onlineboutique"
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 3552
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 3552
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: onlineboutique
spec:
  selector:
    app: cart-service
  ports:
  - port: 3552
    targetPort: 3552
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
  namespace: onlineboutique
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
      - name: checkout-service
        image: onlineboutique/checkout-service:latest
        ports:
        - containerPort: 3553
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: CART_SERVICE_URL
          value: "http://cart-service:3552"
        - name: PRODUCT_CATALOG_SERVICE_URL
          value: "http://product-catalog-service:3550"
        - name: CURRENCY_SERVICE_URL
          value: "http://currency-service:3551"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 3553
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 3553
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  namespace: onlineboutique
spec:
  selector:
    app: checkout-service
  ports:
  - port: 3553
    targetPort: 3553
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: onlineboutique
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: onlineboutique/frontend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: PRODUCT_CATALOG_SERVICE_URL
          value: "http://product-catalog-service:3550"
        - name: CURRENCY_SERVICE_URL
          value: "http://currency-service:3551"
        - name: CART_SERVICE_URL
          value: "http://cart-service:3552"
        - name: CHECKOUT_SERVICE_URL
          value: "http://checkout-service:3553"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: onlineboutique
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onlineboutique-ingress
  namespace: onlineboutique
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: onlineboutique.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 8080
      - path: /api/v1/products
        pathType: Prefix
        backend:
          service:
            name: product-catalog-service
            port:
              number: 3550
      - path: /api/v1/currency
        pathType: Prefix
        backend:
          service:
            name: currency-service
            port:
              number: 3551
      - path: /api/v1/cart
        pathType: Prefix
        backend:
          service:
            name: cart-service
            port:
              number: 3552
      - path: /api/v1/checkout
        pathType: Prefix
        backend:
          service:
            name: checkout-service
            port:
              number: 3553
