server:
  port: 3550
  servlet:
    context-path: /product-catalog

spring:
  application:
    name: product-catalog-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineboutique
    username: ${DB_USERNAME:onlineboutique}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.onlineboutique.catalog: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineboutique_test
    username: ${DB_USERNAME:onlineboutique}
    password: ${DB_PASSWORD:password}

---
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    show-sql: false
  
logging:
  level:
    com.onlineboutique.catalog: INFO
    org.springframework.web: WARN
  file:
    name: /var/log/product-catalog-service.log
